GYROSCOPE_PATH: str = "data/gyroscope"
REAL_IMAGE_PATH: str = "data/images/real"
IDEAL_IMAGE_PATH: str = "data/images/ideal"
RSSI_MODEL_PATH: str = "data/models/rssi.csv"
REAL_OUTPUT_NORMAL_PATH: str = "data/output/real/normal"
REAL_OUTPUT_REVERSED_PATH: str = "data/output/real/reversed"
IDEAL_OUTPUT_NORMAL_PATH: str = "data/output/ideal/normal"
IDEAL_OUTPUT_REVERSED_PATH: str = "data/output/ideal/reversed"
